services:
  nvidia_check:
    image: nvcr.io/nvidia/cuda:11.8.0-devel-ubuntu22.04
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
    command: nvidia-smi
