version: '3'
services:
  nvidia_check:
    image: nvcr.io/nvidia/cuda:11.8.0-devel-ubuntu22.04
    runtime: nvidia
    # Compose Deploy Specification:https://docs.docker.com/compose/compose-file/deploy/ 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # Specifying 'all' for count ensures that all gpu devices are exposed to the
              # container process. As an alternative specific numbers can be provided but that is
              # subjected to additional customization options.
              count: all
              capabilities: ["gpu"]
    command: nvidia-smi
